var searchData=
[
  ['pobierzdane_0',['pobierzDane',['../funkcje_8cpp.html#a444a0a2bf4afcc8ff7ced3fda3684cb4',1,'pobierzDane(std::string nazwaPliku, std::vector&lt; double &gt; &amp;wzrost, std::vector&lt; double &gt; &amp;wyskok):&#160;funkcje.cpp'],['../_funkcje_8h.html#a444a0a2bf4afcc8ff7ced3fda3684cb4',1,'pobierzDane(std::string nazwaPliku, std::vector&lt; double &gt; &amp;wzrost, std::vector&lt; double &gt; &amp;wyskok):&#160;funkcje.cpp']]],
  ['pobierzdrzewo_1',['pobierzDrzewo',['../funkcje_8cpp.html#a670daf8880bc788e437078047b08825b',1,'pobierzDrzewo(std::string nazwaPliku, std::map&lt; int, PunktDrzewaDecyzyjnego &gt; &amp;drzewo, int &amp;indeksMaksymalny):&#160;funkcje.cpp'],['../_funkcje_8h.html#a670daf8880bc788e437078047b08825b',1,'pobierzDrzewo(std::string nazwaPliku, std::map&lt; int, PunktDrzewaDecyzyjnego &gt; &amp;drzewo, int &amp;indeksMaksymalny):&#160;funkcje.cpp']]],
  ['pobierzindeks_2',['pobierzIndeks',['../funkcje_8cpp.html#ade9dd73680a93f0cacaaf7ab5da44529',1,'pobierzIndeks(std::string nazwaPliku, int &amp;indeksMaksymalny):&#160;funkcje.cpp'],['../_funkcje_8h.html#ade9dd73680a93f0cacaaf7ab5da44529',1,'pobierzIndeks(std::string nazwaPliku, int &amp;indeksMaksymalny):&#160;funkcje.cpp']]],
  ['porownaj_3',['porownaj',['../funkcje_8cpp.html#aaa2269208bd708f970a995364b20dca8',1,'porownaj(std::vector&lt; double &gt; &amp;wzrost, std::vector&lt; double &gt; &amp;wyskok, int &amp;indeksMaksymalny, std::vector&lt; double &gt; &amp;koszykowka, std::vector&lt; double &gt; &amp;lekkoatletyka, std::map&lt; int, PunktDrzewaDecyzyjnego &gt; &amp;DrzewoDecyzyjne):&#160;funkcje.cpp'],['../_funkcje_8h.html#aaa2269208bd708f970a995364b20dca8',1,'porownaj(std::vector&lt; double &gt; &amp;wzrost, std::vector&lt; double &gt; &amp;wyskok, int &amp;indeksMaksymalny, std::vector&lt; double &gt; &amp;koszykowka, std::vector&lt; double &gt; &amp;lekkoatletyka, std::map&lt; int, PunktDrzewaDecyzyjnego &gt; &amp;DrzewoDecyzyjne):&#160;funkcje.cpp']]],
  ['projekt_5fsemestralny_5fdrzewo_5fdecyzyjne_5fsekcja06_2ecpp_4',['Projekt_semestralny_drzewo_decyzyjne_sekcja06.cpp',['../_projekt__semestralny__drzewo__decyzyjne__sekcja06_8cpp.html',1,'']]],
  ['punktdrzewadecyzyjnego_5',['PunktDrzewaDecyzyjnego',['../struct_punkt_drzewa_decyzyjnego.html',1,'']]]
];
